env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2017
extends: 'eslint:recommended'
rules:
  semi:
    - warn
    - always
  no-loop-func:
    - error
  strict:
    - warn
    - global
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - error
  comma-style:
    - error
    - last
  comma-spacing:
    - error
    - before: false
      after: true
  func-call-spacing:
    - error
    - never
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: minimum
  keyword-spacing:
    - error
    - before: true
      after: true
      overrides:
        function:
          after: false
  max-len:
    - warn
    - code: 80
      ignoreUrls: true
  max-nested-callbacks:
    - error
    - max: 7
  new-cap:
    - warn
    - newIsCap: true
      capIsNew: true
      properties: true
  new-parens:
    - error
  no-lonely-if:
    - error
  no-trailing-spaces:
    - error
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - after
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
      overrides:
        typeof: false
  no-unreachable:
    - error
  no-global-assign:
    - error
  no-self-compare:
    - error
  no-unmodified-loop-condition:
    - error
  no-console:
    - off
  no-useless-concat:
    - error
  no-useless-escape:
    - error
  no-shadow-restricted-names:
    - error
  no-use-before-define:
    - error
    - functions: false
  no-unused-vars:
    - warn
  no-undef:
    - warn
  arrow-body-style:
    - error
    - as-needed
  arrow-spacing:
    - error
  no-confusing-arrow:
    - error
    - allowParens: true
  no-useless-computed-key:
    - error
  no-useless-rename:
    - error
  no-var:
    - error
  object-shorthand:
    - error
    - always
  prefer-numeric-literals:
    - error
  template-curly-spacing:
    - warn
    - never
  require-atomic-updates:
    - off